package theme

// OpenCode returns the OpenCode dark theme, mirroring the upstream
// packages/tui theme (theme/assets/opencode.json): a 12-step neutral gray
// ramp owns every chrome surface (backgrounds, borders, muted text) while
// three chromatic accents — soft orange primary, blue secondary, purple
// accent — are reserved for live content semantics only.
// bg #0a0a0a → panel #141414 → element #1e1e1e; borders #3c3c3c/#484848/
// #606060 sit between element and muted text.
func OpenCode() *Theme {
	return &Theme{
		Name:                 "opencode",
		BG:                   "#0a0a0a",
		BGHighlight:          "#1e1e1e",
		BGPopup:              "#141414",
		BGStatusline:         "#0a0a0a",
		BGSidebar:            "#141414",
		BGFloat:              "#141414",
		FG:                   "#eeeeee",
		FGFloat:              "#eeeeee",
		Background:           "#0a0a0a",
		BackgroundPanel:      "#141414",
		BackgroundElement:    "#1e1e1e",
		BackgroundMenu:       "#141414",
		Border:               "#484848",
		BorderActive:         "#606060",
		BorderSubtle:         "#3c3c3c",
		Primary:              "#fab283",
		Secondary:            "#5c9cf5",
		Accent:               "#9d7cd8",
		Error:                "#e06c75",
		Warning:              "#f5a742",
		Success:              "#7fd88f",
		Info:                 "#56b6c2",
		Hint:                 "#808080",
		Text:                 "#eeeeee",
		TextMuted:            "#808080",
		TextFaint:            "#606060",
		SelectedListItemText: "#eeeeee",
		TabActive:            "#fab283",
		TabInactive:          "#808080",
		TabActiveBG:          "#1e1e1e",
		UserLabel:            "#fab283",
		AssistantLabel:       "#808080",
		ProfileText:          "#808080",
		ToolName:             "#9d7cd8",
		ToolResult:           "#eeeeee",
		ToolPending:          "#f5a742",
		StatusOK:             "#7fd88f",
		StatusError:          "#e06c75",
		StatusWarn:           "#f5a742",
		DiffAdded:            "#4fd6be",
		DiffRemoved:          "#c53b53",
		DiffContext:          "#808080",
		DiffHunkHeader:       "#9d7cd8",
		DiffHighlight:        "#fab283",
		DiffAddedBg:          "#20303b",
		DiffRemovedBg:        "#37222c",
		DiffContextBg:        "#141414",
		DiffLineNumber:       "#606060",
		DiffLineNumberBg:     "#141414",
		MarkdownText:         "#eeeeee",
		MarkdownHeading:      "#eeeeee",
		MarkdownLink:         "#56b6c2",
		MarkdownLinkText:     "#5c9cf5",
		MarkdownCode:         "#fab283",
		MarkdownBlockQuote:   "#808080",
		MarkdownEmph:         "#fab283",
		MarkdownStrong:       "#eeeeee",
		MarkdownHRule:        "#3c3c3c",
		MarkdownListItem:     "#eeeeee",
		SyntaxComment:        "#808080",
		SyntaxKeyword:        "#9d7cd8",
		SyntaxFunction:       "#fab283",
		SyntaxString:         "#7fd88f",
		SyntaxNumber:         "#56b6c2",
		SyntaxType:           "#5c9cf5",
		SyntaxVariable:       "#eeeeee",
		SyntaxOperator:       "#808080",
		SyntaxPunctuation:    "#808080",
		ThinkingOpacity:      0.6,
	}
}

// OpenCodeTheme is a convenience alias for registration.
var OpenCodeTheme = OpenCode()
