package theme

// PiDark returns the pi dark theme, ported exactly from pi's dark.json
// (see the color mapping table in openspec/changes/redo-tui-pi-style/design.md).
// Every mapped vars+colors entry resolves to the hex below; unmapped entries
// (thinking levels, bashMode, customMessageLabel, searchMatch, scrollbar,
// mdCodeBlock/Border, mdQuoteBorder, export.infoBg) are documented in design.
func PiDark() *Theme {
	return &Theme{
		Name:                 "pi-dark",
		BG:                   "#18181e",
		BGHighlight:          "#1e1e24",
		BGPopup:              "#1e1e24",
		BGStatusline:         "#18181e",
		BGSidebar:            "#18181e",
		BGFloat:              "#1e1e24",
		FG:                   "#d4d4d4",
		FGFloat:              "#d4d4d4",
		Background:           "#18181e",
		BackgroundPanel:      "#1e1e24",
		BackgroundElement:    "#1e1e24",
		BackgroundMenu:       "#1e1e24",
		Border:               "#5f87ff",
		BorderActive:         "#00d7ff",
		BorderSubtle:         "#505050",
		Primary:              "#00d7ff",
		Secondary:            "#81a2be",
		Accent:               "#8abeb7",
		Error:                "#cc6666",
		Warning:              "#ffff00",
		Success:              "#b5bd68",
		Info:                 "#81a2be",
		Hint:                 "#666666",
		Text:                 "#d4d4d4",
		TextMuted:            "#808080",
		TextFaint:            "#666666",
		SelectedListItemText: "#d4d4d4",
		TabActive:            "#808080",
		TabInactive:          "#666666",
		TabActiveBG:          "#1e1e24",
		UserLabel:            "#d4d4d4",
		AssistantLabel:       "#808080",
		ProfileText:          "#808080",
		ToolName:             "#d4d4d4",
		ToolResult:           "#808080",
		ToolPending:          "#ffff00",
		StatusOK:             "#b5bd68",
		StatusError:          "#cc6666",
		StatusWarn:           "#ffff00",
		DiffAdded:            "#b5bd68",
		DiffRemoved:          "#cc6666",
		DiffContext:          "#808080",
		DiffHunkHeader:       "#8abeb7",
		DiffHighlight:        "#f0c674",
		DiffAddedBg:          "#283228",
		DiffRemovedBg:        "#3c2828",
		DiffContextBg:        "#282832",
		DiffLineNumber:       "#666666",
		DiffLineNumberBg:     "#18181e",
		MarkdownText:         "#d4d4d4",
		MarkdownHeading:      "#f0c674",
		MarkdownLink:         "#81a2be",
		MarkdownLinkText:     "#666666",
		MarkdownCode:         "#8abeb7",
		MarkdownBlockQuote:   "#808080",
		MarkdownEmph:         "#d4d4d4",
		MarkdownStrong:       "#d4d4d4",
		MarkdownHRule:        "#808080",
		MarkdownListItem:     "#8abeb7",
		SyntaxComment:        "#6a9955",
		SyntaxKeyword:        "#569cd6",
		SyntaxFunction:       "#dcdcaa",
		SyntaxString:         "#ce9178",
		SyntaxNumber:         "#b5cea8",
		SyntaxType:           "#4ec9b0",
		SyntaxVariable:       "#9cdcfe",
		SyntaxOperator:       "#d4d4d4",
		SyntaxPunctuation:    "#d4d4d4",
		ThinkingOpacity:      0.6,
		UserMessageBg:        "#343541",
		ToolPendingBg:        "#282832",
		ToolSuccessBg:        "#283228",
		ToolErrorBg:          "#3c2828",
		CustomMessageBg:      "#2d2838",
		SelectedBg:           "#3a3a4a",
	}
}

// PiDarkTheme is a convenience alias for registration.
var PiDarkTheme = PiDark()
